### ISSUE TITLE
I am getting below error while installing nuclei

### ISSUE THREAD

**Issue by sreenathr10** [projectdiscovery/fileutil#10]
Getting below error while trying to install nuclei on kali 
```
└─$ GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei                                                                                    126 ⨯
go: found github.com/projectdiscovery/nuclei/v2/cmd/nuclei in github.com/projectdiscovery/nuclei/v2 v2.5.3
github.com/projectdiscovery/fileutil
# github.com/projectdiscovery/fileutil
../go/pkg/mod/github.com/projectdiscovery/fileutil@v0.0.0-20210928100737-cab279c5d4b5/file.go:198:18: undefined: os.CreateTemp

```

**Comment by ehsandeep** [comment]
See this @sreenathr10 https://github.com/projectdiscovery/fileutil/issues/9

**Comment by simrotion13** [comment]
I am also facing same issue...getting below error
# github.com/projectdiscovery/fileutil
Error: ../../../go/pkg/mod/github.com/projectdiscovery/fileutil@v0.0.0-20210926202739-6050d0acf73c/file.go:191:18: undefined: os.CreateTemp

**Comment by ehsandeep** [comment]
@simrotion13 see the above comment, this due to use of outdated version of go, make sure you update it before intalling the nuclei.
